name: Output

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository content
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.9.13

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt

          - name: Execute main.py script
            run: python main.py

          - name: Clone screener-log repository
            run: |
              git clone https://lobiancovitor:${{ secrets.GITHUB_TOKEN }}@github.com/lobiancovitor/screener-log.git

          - name: Copy ratings.csv to screener-log repository
            run: |
              rm ./screener-log/output/* && cp -a ./output/. ./screener-log/output

          - name: push to git
            run: |
              git clone https://lobiancovitor:${{ secrets.GITHUB_TOKEN }}@github.com/lobiancovitor/relative-strength.git
              rm ./relative-strength/output/* && cp -a ./output/. ./relative-strength/output
              cd screener-log
              git config user.name "CI" && git config user.email "ci@github.com"
              git add --all
              git commit -m "CI output update" || echo "nothing to commit"
              git push || echo "nothing to push"

          # - name: Upload ratings.csv as an artifact
          #   uses: actions/upload-artifact@v2
          #   with:
          #     name: ratings.csv
          #     path: output

          # - name: Upload price_history.json as an artifact
          #   uses: actions/upload-artifact@v2
          #   with:
          #     name: price_history.json
          #     path: data