name: Output

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository content
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.9.13

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt

          - name: Execute main.py script
            run: python main.py

          - name: push to git
            run: |
              git clone https://lobiancovitor:${{ secrets.GITHUB_TOKEN }}@github.com/lobiancovitor/relative-strength.git
              rm ./relative-strength/output/* && cp -a ./output/. ./relative-strength/output
              cd relative-strength
              git config user.name "CI" && git config user.email "ci@github.com"
              git add --all
              git commit -m "CI output update" || echo "nothing to commit"
              git push || echo "nothing to push"

          - name: Upload ratings.csv as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: ratings.csv
              path: output
          
          - name: Upload price_history.json as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: price_history.json
              path: output

          - name: push to git
            run: |
              git clone https://lobiancovitor:${{ secrets.GITHUB_TOKEN }}@github.com/lobiancovitor/relative-strength.git
              rm ./relative-strength/market/* && cp -a ./market/. ./relative-strength/market
              cd relative-strength
              git config user.name "CI" && git config user.email "ci@github.com"
              git add --all
              git commit -m "CI output update" || echo "nothing to commit"
              git push || echo "nothing to push"

          - name: Upload $BRA200R.png as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: $BRA200R.png
              path: market

          - name: Upload $BRHL.png as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: $BRHL.png
              path: market

          - name: Upload $BRSI.png as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: $BRSI.png
              path: market