name: Output

on:
  # push:
  #   branches: [ main ]
  schedule:
    - cron: "0 23 * * *"

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository content
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt

          - name: Execute main.py script
            run: python main.py

          - name: push to git
            run: |
              git clone https://lobiancovitor:${{ secrets.GITHUB_TOKEN }}@github.com/lobiancovitor/relative-strength.git
              rm ./relative-strength/output/* && cp -a ./output/. ./relative-strength/output
              cd relative-strength
              git config user.name "CI" && git config user.email "ci@github.com"
              git add --all
              git commit -m "CI output update" || echo "nothing to commit"
              git push || echo "nothing to push"

          - name: Upload rs_stocks.csv as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: rs_stocks.csv
              path: output
