name: Output

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository content
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt

          - name: Execute main.py script
            run: python main.py

          - name: List output directory contents
            run: ls -la output

          - name: Clone relative-strength repo
            run: |
              git clone https://github.com/lobiancovitor/relative-strength.git
              cp output/rs_stocks.csv relative-strength/output/re_stocks.csv

          - name: List relative-strength directory contents
            run: ls -la relative-strength/output

          - name: Add and commit
            uses: EndBug/add-and-commit@v9
            with:
              author_name: GitHub Actions
              author_email: 41898282+github-actions[bot]@users.noreply.github.com
              github_token: ${{ secrets.GITHUB_TOKEN }}
              message: "chore: Update file"
              add: "relative-strength/output/rs_stocks.csv"

          - name: Push changes
            run: |
              cd relative-strength
              git push

          - name: Upload rs_stocks.csv as an artifact
            uses: actions/upload-artifact@v2
            with:
              name: rs_stocks.csv
              path: output/rs_stocks.csv
